artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Ahmad1993Aj/Data/raw/main/brain_tumor_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model #Erstellen folder
  base_model_path: artifacts/prepare_base_model/base_model.h5 #saving Model
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 #saving nach training